// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"tic4303-mini-proj/api"
	"tic4303-mini-proj/dao"
	"tic4303-mini-proj/middleware"
	"tic4303-mini-proj/router"
	"tic4303-mini-proj/service"
)

// Injectors from wire.go:

func initServerRouter() *router.ServerRouter {
	db := middleware.InitMysql()
	userDAO := &dao.UserDAO{
		DB: db,
	}
	userSvc := &service.UserSvc{
		UserDAO: userDAO,
	}
	userApi := &api.UserApi{
		UserSvc: userSvc,
	}
	serverRouter := &router.ServerRouter{
		UserApi: userApi,
	}
	return serverRouter
}
