kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
spec:
  claimRef:
    name: mysql-pvc
    namespace: app-tic4303
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k8s/mysql/mysql-data
