apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: app-tic4303
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: web-app 
        image: web-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

---          

apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: app-tic4303
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: web-app 
